### ISSUE TITLE
Bambora needs to be manually updated to handle recurring gifts

### ISSUE THREAD

**Issue by cjardine-bsc** [BirdStudiesCanada/Website-TO-DO#4]
When a user selects recurring gift on this page: 

https://www.birdscanada.org/support/index.jsp?targetpg=membership&lang=EN

Bambora does not automatically set up a recurring gift, Rosie needs to look at the email generated through the membership page, go into bambora and update them to a recurring gift. 

We should look into whether we can pass bambora the parameter for monthly or annual recurring gifts to save Rosie that manual step.

**Comment by denislepage** [comment]
The form I see on Bambora doesn't seem to support that option. That said, there is another form option that is called pre-authorization, which may be the way to do this.

The list of fields I can pass to the payment form are outlined here:
https://help.na.bambora.com/hc/en-us/articles/115010466568-Building-the-payment-form

There's a recurring payment API, but that's a different approach that would involve more programming.
https://dev.na.bambora.com/docs/guides/recurring_payment/

May be worth looking into later.
